# 애플리케이션 이름
spring.application.name=dorunning

# 공통 서버 설정
server.port=8080

# Naver API 설정
naver.client.id=t5E2hEHo0ylroiIX1ufU
naver.client.secret=NsqmTF6PKk

# 파일 업로드
upload.path=C:/upload
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# [로깅 레벨]
logging.level.root=INFO
logging.level.com.dohwan=INFO
# 로컬 개발 시에만 아래 주석을 해제하거나 local.properties에 넣으세요
# logging.level.com.dohwan=DEBUG

# [인코딩 & 패턴]
logging.charset.console=UTF-8
logging.charset.file=UTF-8
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# [파일 저장 정책]
logging.file.name=logs/dorunning.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# [서블릿 인코딩]
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# JWT Secret
com.dohwan.login.secret-key=2Pyq[MyRMH(DxP'K)ONVI\LB29GD:xbB]?`\{ogZ[}#*)hx7/~68FxK2)HJdCPZ#A&[CBg{v9+T2c122

# MyBatis 공통
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.dohwan.login.domain,com.dohwan.board.domain
mybatis.mapper-locations=classpath*:com/dohwan/**/mapper/*.xml

# PageHelper 공통
pagehelper.reasonable=true
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql

# JPA 공통
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# 기본 profile 지정
spring.profiles.active=prod

# Kakao OAuth2 (OAuth2 login configurations)
com.dohwan.login.kakao-client-id=5406e6e1f9d88cf5ae8af0e02532f34f
com.dohwan.login.kakao-redirect-uri=${KAKAO_REDIRECT_URI:http://localhost:5173/login/kakao}
com.dohwan.login.kakao-client-secret=UK1Qi3PLKw939stSSOtkwvhPf9T6esK4

